### ISSUE TITLE
@pedroprieto. No me funciona el layout plantillablog.html.

### ISSUE THREAD

**Issue by AlfredoAlfred0** [AlfredoAlfred0/plantilla-jekyll#2]
Hola @pedroprieto.

Pues eso, no me genera el listado de los posts.

¿En qué he metido la pata?

Saludos.

**Comment by pedroprieto** [comment]
Buenas,

El código de la plantilla está bien. Lo único, en lugar de poner todo el HTML de nuevo, puedes hacer referencia a la plantilla `layout` y añadir solo lo que es diferente. Así evitas duplicar código.
https://github.com/AlfredoAlfred0/plantilla-jekyll/blob/f85a7fb2dd3a7c3cff61b9c155999b58b6264008/_layouts/plantillablog.html#L1

El problema está en el nombre de los archivos de los posts:
![imagen](https://github.com/AlfredoAlfred0/plantilla-jekyll/assets/7632447/2d7ec214-a949-4fc5-bf2d-c201bebf9940)

Te falta la fecha: https://jekyllrb.com/docs/posts/#creating-posts

Un saludo!

**Comment by AlfredoAlfred0** [comment]
Gracias. Ya está.
